version: "3.8"

services:
  gateway:
    container_name: gateway
    build: ./APIGateWay
    ports:
      - "8000:8000"
    depends_on:
      - auth
      - user
      - email
      - systemlog
      - speechrate

  auth:
    container_name: auth
    build: ./AuthenticationService
    ports:
      - "8001:8001"

  user:
    container_name: user
    build: ./UserService
    ports:
      - "8006:8006"

  # flask:
  #   container_name: flask
  #   build: ./flaskAIservices
  #   ports:
  #     - "8005:8005"

  email:
    container_name: email
    build: ./EmailServices
    ports:
      - "8002:8002"

  systemlog:
    container_name: systemlog
    build: ./SystemLogService
    ports:
      - "8003:8003"

  speechrate:
    container_name: speechrate
    build: ./SpeechRateService
    ports:
      - "8004:8004"
